name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: arch
          - os: macos-latest
            target: macos

    runs-on: ${{ matrix.os }}

    container:
      image: archlinux:latest
      if: matrix.target == 'arch'

    steps:
    - uses: actions/checkout@v4

    # Arch Linux setup
    - name: Install dependencies (Arch)
      if: matrix.target == 'arch'
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm rust jack pkgconf alsa-lib

    # macOS setup
    - name: Install dependencies (macOS)
      if: matrix.target == 'macos'
      run: |
        brew update
        brew install jack pkg-config

    - name: Build
      run: cargo build --verbose

    - name: Clippy
      run: cargo clippy
